baseURL: "https://hugo-profile.netlify.app"
languageCode: "en-us"
title: "Tomé Cerqueira"
theme: "./.."
relativeURLs: true

googleanalytics: UA-167646412-8
disqusShortname:
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true

# menus
disable_extra_menus: true
Menus:
  main:
    - identifier: cv
      name: CV
      title: CV
      url: /CV
      weight: 1

    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /ew
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /34545
    #   parent: dropdown
    #   weight: 2

params:
  version: 3
  customCSS: false

  favicon: "/images/fav.png"
  description: "A high performance hugo theme for personal portfolio and blog."

  # home
  disable_home: false
  profile_image: "/images/profile.png"
  name: "Tomé Cerqueira"
  namecolor: ffc107
  profession: "Software Developer"
  github: "https://github.com/tomecerqueira"
  #gitlab: "https://gitlab.com"
  linkedin: "https://www.linkedin.com/in/tom%C3%A9-cerqueira-156799150/"
  #twitter: "https://twitter.com/"
  #instagram: "https://instagram.com/"
  #facebook: "https://facebook.com"

  #Custom social links
  # customSocialLinks:
  #   - imageURL: "https://hugo-profile.netlify.app/images/fav.png"
  #     url: "https://gohugo.com"
  #   - fontAwesomeIconName: "fa fa-envelope"
  #     url: "https://gmail.com"
  
  # About
  disable_about: false
  descripe_l1_person: "I'm Software Developer/Enginneer based in Porto, Portugal. Currently I'm a Project Manager and Sofware Engineer at ALS Global."
  descripe_l2_person: 'I'm always willing to try new technologies. My core knowledge is in .NET and SQL Server development but I'm loving Python as well. I really am focused in making a "technology carrer change" so I'm putting all my strengths in skilling up at Python!'
  descripe_l3_person: "I consider myself a very enthusiastic, emphatic and straightforward person. Hope you want to know more about me and my projects! You can find my works [here](#projects)"
  skills:
    - name: C#
      percentage: 90
    - name: SQL Server
      percentage: 80
    - name: Flask
      percentage: 50
    - name: Mongo DB
      percentage: 50

  # Experience
  disable_experience: false
  experience:
    - company: "ALS Global"
      # id: "google-developer"   // use this, when you want to change the id(used for navigation)
      role: "Software Developer/Project Manager"
      startdate: Oct 2015
      enddate: present
      featuredpoints:
        - point: Started as Full Stack Junior Developer and continued improving until being a Senior Developer.
        - point: Helping the team achieving their best as Project Manager and as a Developer.

  # Education
  disable_education: false
  education:
    - degree: "Technician"
      branch: "Information Technology"
      university: "Escola Profissional Tondela"
      startedyear: "2012"
      graduation: "2015"

  # Projects
  disable_projects: false
  projects:
    - name: "Currency Converter"
      img: /images/project.jpg
      githublink: "https://github.com/tomecerqueira/currency-converter"
      featuredlink: "/"
      description: "Flask application to convert currencies and commodities. Includes chart with 5 important pairs compared to the Euro and more charts to come"

  # Achievements
  disable_achievements: true
  achievements:
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
      url: https://example.com
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg

  # Contact
  disable_contact: false
  contact_content: Whether you have a question or just want to say hi, I'll try my best to get back to you!
  email: "tcerqueira126@mail.com"

  # Footer
  socialiconfooter: true
  recentposts: false

  # Blog
  showdescription: false
  tweet: false