baseURL: "https://hugo-profile.netlify.app"
languageCode: "en-us"
title: "Tomé Cerqueira"
theme: "./.."
relativeURLs: true

googleanalytics: UA-167646412-8
disqusShortname:
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true

# menus
Menus:
  main:
    # - identifier: blog
    #   name: Blog
    #   title: Blog posts
    #   url: /blog
    #   weight: 1

    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /ew
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /34545
    #   parent: dropdown
    #   weight: 2

params:
  version: 3
  customCSS: false

  favicon: "/images/fav.png"
  description: "A high performance hugo theme for personal portfolio and blog."

  # home
  disable_home: false
  profile_image: "/images/profile.png"
  name: "Tomé Cerqueira"
  namecolor: ffc107
  profession: "Software Developer"
  github: "https://github.com/tomecerqueira"
  #gitlab: "https://gitlab.com"
  linkedin: "https://www.linkedin.com/in/tom%C3%A9-cerqueira-156799150/"
  #twitter: "https://twitter.com/"
  #instagram: "https://instagram.com/"
  #facebook: "https://facebook.com"

  #Custom social links
  # customSocialLinks:
  #   - imageURL: "https://hugo-profile.netlify.app/images/fav.png"
  #     url: "https://gohugo.com"
  #   - fontAwesomeIconName: "fa fa-envelope"
  #     url: "https://gmail.com"
  
  # About
  disable_about: false
  descripe_l1_person: "Hi, I'm Tomé. I've always been a software developer during my (small) carrer. Started programming at 14 and studied it until I was 18.
                       Had the opportunity to this my daily job and grabed it! "
  descripe_l2_person: "Hope you want to know more about me and my projects :smile:. You can find my works [here](#projects)"
  skills:
    - name: C#
      percentage: 90
    - name: SQL Server
      percentage: 80
    - name: Flask
      percentage: 40
    - name: Mongo DB
      percentage: 30

  # Experience
  disable_experience: false
  experience:
    - company: "ALS Global Life Sciences"
      # id: "google-developer"   // use this, when you want to change the id(used for navigation)
      role: "Software Developer / Project Manager"
      startdate: Oct 2015
      enddate: present
      featuredpoints:
        - point: Started as Full Stack Junior Developer and continued improving until being a Senior Developer.
      startdate: Sep 2020
      enddate: present
      featuredpoints:
        - point: Helping the team achieving their best as Project Manager and as a Developer.
  # Education
  disable_education: false
  education:
    - degree: "Technician"
      branch: "Information Technology"
      university: "Escola Profissional Tondela"
      startedyear: "2012"
      graduation: "2015"

  # Projects
  disable_projects: false
  projects:
    - name: "Example project without details"
      img: /images/project.jpg
      githublink: "https://github.com/"
      featuredlink: "/"
      description: "Description of project"

  # Achievements
  disable_achievements: false
  achievements:
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
      url: https://example.com
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg

  # Contact
  disable_contact: false
  contact_content: My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you!
  email: "tcerqueira126@mail.com"

  # Footer
  socialiconfooter: true
  recentposts: true

  # Blog
  showdescription: false
  tweet: false
